# Generated by Django 3.2 on 2022-02-17 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20220217_0328'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='for_sale',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='article',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
