# Generated by Django 3.2 on 2022-02-18 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_lecteur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='like',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
